### ISSUE TITLE
Gateway URL

### ISSUE THREAD

**Issue by vlados** [gentor/omnipay-borica#1]
Hi,
I am seeing that you are using https://3dsgate.borica.bg for the URL of the API, but when I try to make a purchase is redirecting me to Borica with error:
```
Sorry, due to technical fault your request cannot be processed
Error message: Bad CGI request
Please try once again or visit us later or choose another means of payment.
```
What is the difference between both URLs and how I can change the URL without manipulating the package?

**Comment by vlados** [comment]
I received an response from Borica explaining that this is the new protocol ... from 2018 ...
I am waiting and for explanation about the error and how I can debug the errors like this

**Comment by vanssata** [comment]
@vlados This is two different payment methods, for use this you need to regenerate new tokens(keys), and endpoints. 
For old borica API you need to use another plugin. Something like [Old Borica](https://github.com/mirovit/borica-api)

**Comment by vlados** [comment]
Yes, After 15 e-mails I understood that the old borica payment gateway will stop working at the end of 2020 ...
